version: "3.8"

services:

  app:
    build: .
    container_name: node-app

    ports:
      - "3000:3000"

    depends_on:
      - mongodb

    restart: always

  mongodb:
    image: mongo:7

    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    restart: always

volumes:
  mongo-data:
